[mypy]

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-tomli_w.*]
ignore_missing_imports = True

[mypy-nightskycam_scorer.*]
ignore_missing_imports = True

[mypy-auto_stretch.*]
ignore_missing_imports = True

